name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get Updater Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.UPDATE_APP_ID}}
          private_key: ${{secrets.UPDATE_APP_KEY}}
      - name: stuff
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          DESTINATION_BRANCH: test
        run: |
          echo -e "\n $(date)" >> README.md
          git add README.md
          git config user.name 'Example'
          git config user.email 'example@example.org'
          git commit -m 'test?'

          # TOKEN=${{ steps.generate-token.outputs.token }}
          git push https://$TOKEN@github.com/cole-h/test.git HEAD:test || exit 1
          exit 0

          # set -x
          # export CONTENT=$( base64 -i README.md )
          # export BASE=$DESTINATION_BRANCH
          # if gh api --method GET /repos/:owner/:repo/git/refs/heads/$DESTINATION_BRANCH; then
          #   git fetch origin $DESTINATION_BRANCH
          # else
          #   export BASE=$(gh repo view --json defaultBranchRef --template '{{ .defaultBranchRef.name }}' ${{github.repository}})
          #   export BASE_SHA=$( git rev-parse origin/$BASE )
          #   gh api --method POST /repos/:owner/:repo/git/refs \
          #     --field ref=refs/heads/$DESTINATION_BRANCH \
          #     --field sha=$BASE_SHA
          # fi
          # export BASE_SHA=$( git rev-parse origin/$BASE )
          # export SHA=$( git rev-parse origin/$BASE:README.md )
          # gh api --method PUT /repos/:owner/:repo/contents/README.md \
          #   --field message="test 2" \
          #   --field content="$CONTENT" \
          #   --field encoding="base64" \
          #   --field branch="$DESTINATION_BRANCH" \
          #   --field sha="$SHA"
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test
          delete-branch: true
          committer: "Example <example@example.org>"
          author: "Example <example@example.org>"
          title: "testing pr"
          token: ${{ steps.generate-token.outputs.token }}
          body: "job's done"
