name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get Updater Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.UPDATE_APP_ID}}
          private_key: ${{secrets.UPDATE_APP_KEY}}
      - name: lol
        run: |
            echo -e "\n$(date)" >> README.md
      - name: branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          branch: refs/heads/test
      - name: Commit file
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          files: |
            README.md
          commit-message: commit mesasge
          ref: refs/heads/test
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test
          delete-branch: true
          committer: "Example <example@example.org>"
          author: "Example <example@example.org>"
          title: "testing pr"
          token: ${{ steps.generate-token.outputs.token }}
          body: "job's done"
